# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.namespace }}
type: {{.Values.secrets.type}}
data:
  {{- include "rag-service.secrets" .| indent 2}}